apiVersion: apps/v1
kind: Deployment
metadata:
  name: holiday
  namespace: holiday
spec:
  selector:
    matchLabels:
      app: holiday
  replicas: 1
  template:
    metadata:
      labels:
        app: holiday
    spec:
      containers:
      - name: holiday
        image: ramdanariadi/holiday-service
        imagePullPolicy: Always
        ports:
          - containerPort: 10000
        env:
          - name: CORE_SERVICE_URL
            value: 'http://core-service.core.svc.cluster.local:10001'

---

apiVersion: v1
kind: Service
metadata:
  name: holiday-service
  namespace: holiday
  labels:
    service: holiday-service
spec:
  selector:
    app: holiday
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 10000

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: holiday
  # annotations:
  #   kubernetes.digitalocean.com/load-balancer-id: "your-load-balancer-id"
  #   service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
  #   service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: holiday
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 10000
